replicas: 40
container:
  name: nginx-container-prod
  image:
    name: nginx
    tag: 1.27-alpine
  port: 80

service:
  port: 80

env:
  enabled: true
  FLAG: "amit"
  LOG_LEVEL: "verbose"
  sads: "amit"
  fdf: "kumar"
  hgh: "amit"
  LOvcG_LEVEL: "kumar"
