apiVersion: apps/v1
kind: Deployment
metadata:
  name: cd-demo-stable
  namespace: app-production
spec:
  replicas: 4
  selector:
    matchLabels:
      app: cd-demo
      env: production
      track: stable
  template:
    metadata:
      labels:
        app: cd-demo
        env: production
        track: stable
      annotations:
        deployment.kubernetes.io/revision: "replace-this-version"
    spec:
      containers:
        - name: cd-demo
          image: aaamiiit/cd-app:replace-this-version
          ports:
            - containerPort: 5000
          env:
            - name: APP_ENV
              value: "production"
            - name: APP_VERSION
              valueFrom:
                fieldRef:
                  fieldPath: metadata.annotations['deployment.kubernetes.io/revision']
            - name: APP_COLOR
              value: "stable"