apiVersion: v1
kind: Service
metadata:
  name: cd-demo-bluegreen
  namespace: app-production
  labels:
    app: app-production
spec:
  selector:
    app: cd-demo
    env: production
    color: blue # initial color version
  ports:
    - port: 80
      targetPort: 5000
      nodePort: 30081
  type: NodePort