apiVersion: v1
kind: Service
metadata:
  name: cd-demo-staging
  namespace: app-staging
  labels:
    app: app-staging
spec:
  selector:
    app: cd-demo
    env: staging
  ports:
    - port: 80
      targetPort: 5000
      nodePort: 30080
  type: NodePort